extends Node

enum GAME_STATES {INTRO, MENU, DEATH, GAME}

enum DIRECTIONS {LEFT, RIGHT}

enum PLAYER_STATES {IDLE, TRANSITION, BLOCKED}

enum ENGINE_DIRECTIONS {LEFT, RIGHT, CENTER}

enum WALL_TYPES {EMPTY, FAT, STAFF_FAT, STAFF_ONLY}

enum SPED_STATES {IDLE, SPEEDUP, SPEEDDOWN}

const SPEED = 150

const SPEEDUP = 10

const SPEEDUPSTEPS = 10

var SAVE_DATA

const SAVE_DEFAULT = {
	'scores' : 0,
	'sound' : true,
}
